### PR TITLE
Add spaces before readings

### PR DESCRIPTION
**Pull request by omergreen**
Fix issues #32 and #29

### CODE REVIEW

**Comment by omergreen** [comment]
We should probably also strip spaces from the sentence when removing furigana?

**Comment by obynio** [comment]
Hello @omergreen, that's a good change. Concerning your suggestion, yes please, can you please make sure to remove the spaces from the sentence when removing furiganas ?

**Comment by omergreen** [comment]
Done, I've also updated the tests and made sure they pass

**Comment by obynio** [comment]
This was tested, merged and release in 1.4.6. Thank you for your contribution 🫡

**Pull request merged**
